
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
        args: ['--unsafe']
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: lint-rust
        name: Lint Rust
        entry: just lint
        types: [rust]
        language: system
        pass_filenames: false
